- hosts: all
  become: true
  tasks:
    - name: Full system upgrade
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: full

    - name: Reboot all hosts
      ansible.builtin.reboot:
        reboot_timeout: 3600
      async: 0
      poll: 0
      ignore_errors: true
      become: true
      notify: Reboot_check

    - name: Heartbeat check
      ansible.builtin.ping:

    - name: Getting host information
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }} running {{ ansible_distribution }} > {{ ansible_distribution_version }}"

  handlers:
    - name: Reboot_check
      ansible.builtin.wait_for_connection:
        timeout: 300
        delay: 10
