---
- hosts: all
  become: true
  tasks:
    - name: Full system upgrade
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: full
    - name: Reboot all hosts
      reboot:
        reboot_timeout: 3600
    - name: Heartbeat check
      ansible.builtin.ping:
    - name: Getting host information
      debug: msg="{{ ansible_hostname }} running {{ ansible_distribution }} > {{ ansible_distribution_version }}"