---
- hosts: all
  gather_facts: yes
  become: false
  tasks:
  - name: Get host name and distro
    debug: msg="{{ansible_hostname}} running {{ ansible_distribution }} > {{ ansible_distribution_version}}"
