ungrouped:
  hosts:
    localhost:
      ansible_user: soyun
    kms.int.s0yun.xyz:
      ansible_user: soyun
    plex.infra.int.s0yun.xyz:
      ansible_user: soyun
    proxy.infra.int.s0yun.xyz:
      ansible_user: soyun
    unifi.int.s0yun.xyz:
      ansible_user: soyun
    vpn.infra.int.s0yun.xyz:
      ansible_user: soyun
    photos.infra.int.s0yun.xyz:
      ansible_user: soyun
    oci.s0yun.xyz:
      ansible_user: ubuntu
    adguard.infra.int.s0yun.xyz:
      ansible_user: soyun

docker:
  hosts:
    docker01.infra.int.s0yun.xyz:
      ansible_user: soyun
    docker02.infra.int.s0yun.xyz:
      ansible_user: soyun
