- name: Package install
  hosts: localhost

  tasks:
    - name: Install commonly used tools
      become: true
      ansible.builtin.apt:
        pkg: "{{ aptpkgs }}"
        state: present
  vars:
    aptpkgs:
      - sipcalc
      - whois
