- name: Regular maintance
  hosts: all
  become: true
  tasks:
    - name: Upgrade all packages after updating the apt cache.
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      register: apt_upgrade

    - name: List installed and updated packages I # noqa no-changed-when
      ansible.builtin.shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result
      when: apt_upgrade.changed

    - name: List upgraded packages II # noqa no-changed-when
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines }}"
      when: apt_upgrade.changed

    - name: Remove unused dependency packages
      ansible.builtin.apt:
        autoremove: true
      register: dependancy_clean

    - name: Search DPGK for removed packages I # noqa no-changed-when
      ansible.builtin.shell: grep -E "^$(date +%Y-%m-%d).+ (remove) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result
      when: dependancy_clean.changed

    - name: List removed packages II # noqa no-changed-when
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines }}"
      when: dependancy_clean.changed
