- hosts: all
  become: yes
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Upgrade all packages after updating the apt cache.
      apt:
        upgrade: yes
      register: debian
    - name: List installed and updated packages I
      shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result
      when: debian.changed
    - name: List installed and updated packages I
      debug: msg="{{ result.stdout_lines }}"
      when: debian.changed
    - name: Remove unused dependency packages
      apt:
        autoremove : yes
      register: dependancy-clean
    - name: Search DPGK for removed packages I
      shell: grep -E "^$(date +%Y-%m-%d).+ (remove) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result
      when: dependancy-clean.changed
    - name: List removed packages II
      debug: msg="{{ result.stdout_lines }}"
      when: dependancy-clean.changed