- name: Regular maintance
  hosts: all
  become: true
  tasks:
    - name: Upgrade all packages after updating the apt cache.
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Remove unused dependency packages
      ansible.builtin.apt:
        autoremove: true

    - name: Getting host information
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }} running {{ ansible_distribution }} > {{ ansible_distribution_version }}"

    - name: Check Shell # noqa no-changed-when
      ansible.builtin.shell:
        echo $SHELL
      register: shell_output

    - name: Print Shell Information
      ansible.builtin.debug:
        msg: "The current shell is {{ shell_output.stdout }}"
