- name: Regular maintance for apt
  hosts: all
  become: true
  tasks:
    - name: Upgrade all packages after updating the apt cache.
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      register: apt_upgrade

    # - name: List installed and updated packages I # noqa no-changed-when
    #   ansible.builtin.shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
    #   register: result
    #   when: debian.changed

    - name: List installed and updated packages I # noqa no-handler
      ansible.builtin.debug:
        msg: >-
          {% for line in apt_upgrade.stdout_lines %}
          {% if line.startswith('Unpacking') %}
          {{ line | regex_replace('^Unpacking\s(.*?)(:.*?)?\s\((.*?)\)\sover\s\((.*?)\).*$', '\1') }}
          {{ line | regex_replace('^Unpacking\s(.*?)(:.*?)?\s\((.*?)\)\sover\s\((.*?)\).*$', '\4') }} ->
          {{ line | regex_replace('^Unpacking\s(.*?)(:.*?)?\s\((.*?)\)\sover\s\((.*?)\).*$', '\3') }}

          {% endif %}
          {% endfor %}
      when: apt_upgrade.changed

    - name: Remove unused dependency packages
      ansible.builtin.apt:
        autoremove: true
      register: dependancy_clean

    - name: Search DPGK for removed packages I # noqa no-changed-when
      ansible.builtin.shell: grep -E "^$(date +%Y-%m-%d).+ (remove) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result
      when: dependancy_clean.changed

    - name: List removed packages II # noqa no-changed-when
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines }}"
      when: dependancy_clean.changed
