- name: SSH Hardening
  hosts: all
  gather_facts: true

  tasks:
    - name: Ensure all needed keys are present
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: https://github.com/s0yun.keys

    - name: Ensure SSH Key Authentication is Enabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^(#)?\s*PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
      notify: Restart SSH
      become: true

    - name: Disable Password Authentication in SSH Config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^(#)?\s*PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH
      become: true

    - name: Disable Root Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^(#)?\s*PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH
      become: true

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: true
