---
- name: Check and Install Starship
  hosts: all
  gather_facts: false

  tasks:
    - name: Check if Starship is installed
      ansible.builtin.shell:
        cmd: starship --version
      register: starship_output
      failed_when: false

    - name: Install Starship using FQCN
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.general.starship
      when: starship_output.rc != 0

    - name: Verify Starship installation
      ansible.builtin.shell:
        cmd: starship --version
      register: starship_output

    - name: Print Starship version
      ansible.builtin.debug:
        msg: "Starship version: {{ starship_output.stdout }}"
