- name: Update starship.rs shell
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Ensure curl is installed
      ansible.builtin.package:
        name: curl
        state: present

    - name: Download starship.rs update script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_update.sh
        mode: '0755'

    - name: Run starship.rs update script
      ansible.builtin.shell: /tmp/starship_update.sh -y
      args:
        executable: /bin/bash
      register: starship_update_result
      changed_when: starship_update_result.stdout_lines | length > 0

    - name: Verify Starship installation
      ansible.builtin.shell:
        cmd: starship --version
      register: starship_output

    - name: Print Starship version
      ansible.builtin.debug:
        msg: "Starship version: {{ starship_output.stdout }}"
