--- 
- hosts: all
  tasks:
    - name: Download starship config
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/s0yun/dotfiles/main/starship.toml
        dest: /home/{{ ansible_user }}/.config/starship.toml
