---
- hosts: 127.0.0.1
  tasks:
    - name: Installing all packages
      community.general.homebrew:
        name: "{{ packages }}"
      state: latest
      register: changed_pkg
    - name: What packages have been installed 
      debug:
      msg: "{{ changed_pkg }}"
  vars:
    packages:
      - bitwarden
      - iterm2
      - firefox
      - visual-studio-code
      - starship
      - ansible-lint
      - spotify
      - packer
      - git