---
- hosts: 127.0.0.1
  tasks:
    - name: Updating homebrew
      community.general.homebrew:
        update_homebrew: yes
    - name: Updating all packages
      community.general.homebrew:
        upgrade_all: yes
        register: changed_pkg
    - name: Verbose output
      debug:
        msg: "{{ changed_pkg }}"