---
name: Ansible Lint 
on: [push, pull_request]
jobs:
  ansible:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Lint Ansible Playbooks
      uses: ansible/ansible-lint-action@main
      with:
        targets: |
          "./*.yml"
          "./macos/*.yml"
        override-deps: |
          rich>=9.5.1,<11.0.0